// export const FETCH_TODO_REQUEST = 'FETCH_TODO_REQUEST';
// export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
// export const FETCH_TODO_FAILURE = 'FETCH_TODO_FAILURE';

export const FETCH_NOTE_REQUEST = 'FETCH_NOTE_REQUEST';
export const ACTION_NOTE_SUCCESS = 'ACTION_NOTE_SUCCESS';
export const ACTION_NOTE_FAILURE = 'ACTION_NOTE_FAILURE';
export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST';
