// export const FETCH_TODO_REQUEST = 'FETCH_TODO_REQUEST';
// export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
// export const FETCH_TODO_FAILURE = 'FETCH_TODO_FAILURE';

export const ACTION_NOTE_FAILURE = 'ACTION_NOTE_FAILURE';
export const FETCH_NOTE_REQUEST = 'FETCH_NOTE_REQUEST';
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const UPDATE_NOTE_REQUEST = 'UPDATE_NOTE_REQUEST';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const FOCUS_NOTE = 'FOCUS_NOTE';
